/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nativecode_impl_NativeService */

#ifndef _Included_com_nativecode_impl_NativeService
#define _Included_com_nativecode_impl_NativeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nativecode_impl_NativeService
 * Method:    getMsgFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nativecode_impl_NativeService_getMsgFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
